// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	CookieAuthScopes cookieAuthContextKey = "cookieAuth.Scopes"
)

// Defines values for AuthTokenResponseTokenType.
const (
	Bearer AuthTokenResponseTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the AuthTokenResponseTokenType enum.
func (e AuthTokenResponseTokenType) Valid() bool {
	switch e {
	case Bearer:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Degraded HealthStatus = "degraded"
	Ok       HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Degraded:
		return true
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for InstanceStatus.
const (
	InstanceStatusError    InstanceStatus = "error"
	InstanceStatusFrozen   InstanceStatus = "frozen"
	InstanceStatusRunning  InstanceStatus = "running"
	InstanceStatusStarting InstanceStatus = "starting"
	InstanceStatusStopped  InstanceStatus = "stopped"
	InstanceStatusStopping InstanceStatus = "stopping"
)

// Valid indicates whether the value is a known member of the InstanceStatus enum.
func (e InstanceStatus) Valid() bool {
	switch e {
	case InstanceStatusError:
		return true
	case InstanceStatusFrozen:
		return true
	case InstanceStatusRunning:
		return true
	case InstanceStatusStarting:
		return true
	case InstanceStatusStopped:
		return true
	case InstanceStatusStopping:
		return true
	default:
		return false
	}
}

// Defines values for InstanceType.
const (
	InstanceTypeContainer      InstanceType = "container"
	InstanceTypeVirtualMachine InstanceType = "virtual-machine"
)

// Valid indicates whether the value is a known member of the InstanceType enum.
func (e InstanceType) Valid() bool {
	switch e {
	case InstanceTypeContainer:
		return true
	case InstanceTypeVirtualMachine:
		return true
	default:
		return false
	}
}

// Defines values for InstanceCreateType.
const (
	InstanceCreateTypeContainer      InstanceCreateType = "container"
	InstanceCreateTypeVirtualMachine InstanceCreateType = "virtual-machine"
)

// Valid indicates whether the value is a known member of the InstanceCreateType enum.
func (e InstanceCreateType) Valid() bool {
	switch e {
	case InstanceCreateTypeContainer:
		return true
	case InstanceCreateTypeVirtualMachine:
		return true
	default:
		return false
	}
}

// Defines values for OperationStatus.
const (
	OperationStatusCancelled OperationStatus = "cancelled"
	OperationStatusFailure   OperationStatus = "failure"
	OperationStatusPending   OperationStatus = "pending"
	OperationStatusRunning   OperationStatus = "running"
	OperationStatusSuccess   OperationStatus = "success"
)

// Valid indicates whether the value is a known member of the OperationStatus enum.
func (e OperationStatus) Valid() bool {
	switch e {
	case OperationStatusCancelled:
		return true
	case OperationStatusFailure:
		return true
	case OperationStatusPending:
		return true
	case OperationStatusRunning:
		return true
	case OperationStatusSuccess:
		return true
	default:
		return false
	}
}

// Defines values for ListInstancesParamsStatus.
const (
	ListInstancesParamsStatusError   ListInstancesParamsStatus = "error"
	ListInstancesParamsStatusFrozen  ListInstancesParamsStatus = "frozen"
	ListInstancesParamsStatusRunning ListInstancesParamsStatus = "running"
	ListInstancesParamsStatusStopped ListInstancesParamsStatus = "stopped"
)

// Valid indicates whether the value is a known member of the ListInstancesParamsStatus enum.
func (e ListInstancesParamsStatus) Valid() bool {
	switch e {
	case ListInstancesParamsStatusError:
		return true
	case ListInstancesParamsStatusFrozen:
		return true
	case ListInstancesParamsStatusRunning:
		return true
	case ListInstancesParamsStatusStopped:
		return true
	default:
		return false
	}
}

// Defines values for ListOperationsParamsStatus.
const (
	ListOperationsParamsStatusCancelled ListOperationsParamsStatus = "cancelled"
	ListOperationsParamsStatusFailure   ListOperationsParamsStatus = "failure"
	ListOperationsParamsStatusPending   ListOperationsParamsStatus = "pending"
	ListOperationsParamsStatusRunning   ListOperationsParamsStatus = "running"
	ListOperationsParamsStatusSuccess   ListOperationsParamsStatus = "success"
)

// Valid indicates whether the value is a known member of the ListOperationsParamsStatus enum.
func (e ListOperationsParamsStatus) Valid() bool {
	switch e {
	case ListOperationsParamsStatusCancelled:
		return true
	case ListOperationsParamsStatusFailure:
		return true
	case ListOperationsParamsStatusPending:
		return true
	case ListOperationsParamsStatusRunning:
		return true
	case ListOperationsParamsStatusSuccess:
		return true
	default:
		return false
	}
}

// AuthTokenEnvelope JSON envelope returned by auth flows that issue or continue a session.
type AuthTokenEnvelope struct {
	// Data Auth response data for password and MFA flows.
	Data AuthTokenResponse `json:"data"`
}

// AuthTokenResponse Auth response data for password and MFA flows.
type AuthTokenResponse struct {
	// AccessToken Ed25519-signed JWT access token. Present when MFA is not required or after MFA completion.
	AccessToken string `json:"access_token,omitempty"`

	// ExpiresIn Access-token lifetime in seconds.
	ExpiresIn int `json:"expires_in,omitempty"`

	// MfaRequired True when the password was accepted but TOTP or a recovery code is still required.
	MfaRequired bool `json:"mfa_required"`

	// MfaToken Opaque pre-session MFA token. Present only when `mfa_required` is true.
	MfaToken string `json:"mfa_token,omitempty"`

	// TokenType Bearer token type for the access token.
	TokenType AuthTokenResponseTokenType `json:"token_type,omitempty"`
}

// AuthTokenResponseTokenType Bearer token type for the access token.
type AuthTokenResponseTokenType string

// Error Standard error envelope returned by 4xx and 5xx responses.
type Error struct {
	// Code Stable, machine-readable error code.
	Code string `json:"code"`

	// Details Optional structured context.
	Details map[string]interface{} `json:"details,omitempty"`

	// Message Human-readable message.
	Message string `json:"message"`
}

// Health Daemon liveness payload.
type Health struct {
	// IncusReachable True when the Incus socket responded to the last probe.
	IncusReachable bool `json:"incus_reachable,omitempty"`

	// Status Aggregate daemon health state.
	Status HealthStatus `json:"status"`
}

// HealthStatus Aggregate daemon health state.
type HealthStatus string

// Instance Container or virtual-machine instance snapshot.
type Instance struct {
	// Architecture CPU architecture.
	Architecture string `json:"architecture,omitempty"`

	// CreatedAt Instance creation timestamp (RFC 3339).
	CreatedAt time.Time `json:"created_at,omitempty"`

	// Image Source image alias or fingerprint.
	Image string `json:"image,omitempty"`

	// Ipv4 IPv4 addresses assigned to the instance.
	Ipv4 []string `json:"ipv4,omitempty"`

	// Ipv6 IPv6 addresses assigned to the instance.
	Ipv6 []string `json:"ipv6,omitempty"`

	// Name Instance name (Incus identifier).
	Name string `json:"name"`

	// Status Current lifecycle state.
	Status InstanceStatus `json:"status"`

	// Type Instance kind reported by Incus.
	Type InstanceType `json:"type"`
}

// InstanceStatus Current lifecycle state.
type InstanceStatus string

// InstanceType Instance kind reported by Incus.
type InstanceType string

// InstanceCreate Request body for `POST /instances`.
type InstanceCreate struct {
	// Image Image alias or fingerprint. Examples: `images:debian/13`,
	// `images:ubuntu/24.04`, or a sha256 fingerprint.
	Image string `json:"image"`

	// Name Desired instance name.
	Name string `json:"name"`

	// Start If true, start immediately after creation.
	Start bool `json:"start,omitempty"`

	// Type Instance kind to create.
	Type InstanceCreateType `json:"type,omitempty"`
}

// InstanceCreateType Instance kind to create.
type InstanceCreateType string

// InstanceStopRequest Optional body for `POST /instances/{name}/stop`.
type InstanceStopRequest struct {
	// Force If true, send SIGKILL after timeout instead of SIGTERM grace.
	Force bool `json:"force,omitempty"`

	// TimeoutSeconds Seconds to wait for graceful shutdown before forcing.
	TimeoutSeconds int `json:"timeout_seconds,omitempty"`
}

// LoginRequest Username + password credentials submitted to `/auth/login`.
type LoginRequest struct {
	// Password Account password (cleartext over TLS only).
	Password string `json:"password"`

	// Username Account username.
	Username string `json:"username"`
}

// MFACompleteRequest TOTP or recovery-code proof for a pre-session MFA challenge.
type MFACompleteRequest struct {
	// MfaToken Opaque pre-session challenge token returned by `/auth/login`.
	MfaToken string `json:"mfa_token"`

	// RecoveryCode One-time recovery code shown during TOTP enrollment.
	RecoveryCode string `json:"recovery_code,omitempty"`

	// TotpCode Six-digit TOTP code from the user's authenticator app.
	TotpCode string `json:"totp_code,omitempty"`
}

// Operation Async operation tracking record.
type Operation struct {
	// CreatedAt Operation submission time (RFC 3339).
	CreatedAt time.Time `json:"created_at"`

	// Error Present when status is `failure`.
	Error string `json:"error,omitempty"`

	// Id Operation identifier (UUID v7).
	Id openapi_types.UUID `json:"id"`

	// Kind Operation kind, e.g. `instance.create` or `instance.delete`.
	Kind string `json:"kind"`

	// ProgressPercent Approximate progress between 0 and 100 (best-effort).
	ProgressPercent int `json:"progress_percent,omitempty"`

	// Status Current operation lifecycle state.
	Status OperationStatus `json:"status"`

	// Target Resource the operation acts on (e.g. instance name).
	Target string `json:"target,omitempty"`

	// UpdatedAt Last state-change time (RFC 3339).
	UpdatedAt time.Time `json:"updated_at"`
}

// OperationStatus Current operation lifecycle state.
type OperationStatus string

// SetupRequest First-admin credentials plus the installer setup token.
type SetupRequest struct {
	// Password Initial admin password.
	Password string `json:"password"`

	// SetupToken One-time setup token read from `/etc/helling/setup-token`.
	SetupToken string `json:"setup_token"`

	// Username Initial admin username.
	Username string `json:"username"`
}

// SetupStatus First-admin setup availability.
type SetupStatus struct {
	// SetupRequired True while no users exist and `/auth/setup` can create the first admin.
	SetupRequired bool `json:"setup_required"`
}

// User Authenticated user identity.
type User struct {
	// CreatedAt Account creation time (RFC 3339).
	CreatedAt time.Time `json:"created_at"`

	// Id Stable user identifier.
	Id int64 `json:"id"`

	// IsAdmin True for the bootstrap admin user.
	IsAdmin bool `json:"is_admin"`

	// Username Account username.
	Username string `json:"username"`
}

// Version Server build metadata.
type Version struct {
	// ApiVersion REST API major-version path segment.
	ApiVersion string `json:"api_version"`

	// BuildTime Build timestamp (RFC 3339 / ISO 8601).
	BuildTime time.Time `json:"build_time,omitempty"`

	// Commit Git commit short SHA the binary was built from.
	Commit string `json:"commit,omitempty"`

	// Version Daemon semantic version string.
	Version string `json:"version"`
}

// InstanceName Instance name. Lowercase letters, digits, and hyphens only.
// Max 63 chars. Must start with letter or digit.
type InstanceName = string

// BadRequest Standard error envelope returned by 4xx and 5xx responses.
type BadRequest = Error

// Conflict Standard error envelope returned by 4xx and 5xx responses.
type Conflict = Error

// NotFound Standard error envelope returned by 4xx and 5xx responses.
type NotFound = Error

// RateLimited Standard error envelope returned by 4xx and 5xx responses.
type RateLimited = Error

// ServiceUnavailable Standard error envelope returned by 4xx and 5xx responses.
type ServiceUnavailable = Error

// Unauthorized Standard error envelope returned by 4xx and 5xx responses.
type Unauthorized = Error

// cookieAuthContextKey is the context key for cookieAuth security scheme
type cookieAuthContextKey string

// ListInstancesParams defines parameters for ListInstances.
type ListInstancesParams struct {
	// Status Optional status filter
	Status ListInstancesParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// ListInstancesParamsStatus defines parameters for ListInstances.
type ListInstancesParamsStatus string

// ListOperationsParams defines parameters for ListOperations.
type ListOperationsParams struct {
	// Status Optional status filter for operations.
	Status ListOperationsParamsStatus `form:"status,omitempty" json:"status,omitempty"`

	// Limit Maximum number of results to return.
	Limit int `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListOperationsParamsStatus defines parameters for ListOperations.
type ListOperationsParamsStatus string

// AuthLoginJSONRequestBody defines body for AuthLogin for application/json ContentType.
type AuthLoginJSONRequestBody = LoginRequest

// AuthMfaCompleteJSONRequestBody defines body for AuthMfaComplete for application/json ContentType.
type AuthMfaCompleteJSONRequestBody = MFACompleteRequest

// AuthSetupJSONRequestBody defines body for AuthSetup for application/json ContentType.
type AuthSetupJSONRequestBody = SetupRequest

// CreateInstanceJSONRequestBody defines body for CreateInstance for application/json ContentType.
type CreateInstanceJSONRequestBody = InstanceCreate

// StopInstanceJSONRequestBody defines body for StopInstance for application/json ContentType.
type StopInstanceJSONRequestBody = InstanceStopRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Exchange username + password for a session
	// (POST /auth/login)
	AuthLogin(w http.ResponseWriter, r *http.Request)
	// Invalidate the current session
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Identity of the authenticated user
	// (GET /auth/me)
	GetCurrentUser(w http.ResponseWriter, r *http.Request)
	// Complete a pre-session MFA challenge
	// (POST /auth/mfa/complete)
	AuthMfaComplete(w http.ResponseWriter, r *http.Request)
	// Create the first admin user
	// (POST /auth/setup)
	AuthSetup(w http.ResponseWriter, r *http.Request)
	// Report whether first-admin setup is required
	// (GET /auth/setup/status)
	AuthSetupStatus(w http.ResponseWriter, r *http.Request)
	// Liveness probe
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// List instances visible to the user
	// (GET /instances)
	ListInstances(w http.ResponseWriter, r *http.Request, params ListInstancesParams)
	// Create a new instance (async)
	// (POST /instances)
	CreateInstance(w http.ResponseWriter, r *http.Request)
	// Delete an instance (async)
	// (DELETE /instances/{name})
	DeleteInstance(w http.ResponseWriter, r *http.Request, name InstanceName)
	// Fetch a single instance
	// (GET /instances/{name})
	GetInstance(w http.ResponseWriter, r *http.Request, name InstanceName)
	// Start an instance (async)
	// (POST /instances/{name}/start)
	StartInstance(w http.ResponseWriter, r *http.Request, name InstanceName)
	// Stop an instance (async)
	// (POST /instances/{name}/stop)
	StopInstance(w http.ResponseWriter, r *http.Request, name InstanceName)
	// List operations for the current user
	// (GET /operations)
	ListOperations(w http.ResponseWriter, r *http.Request, params ListOperationsParams)
	// Fetch a single operation by ID
	// (GET /operations/{id})
	GetOperation(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Server version and build info
	// (GET /version)
	GetVersion(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Exchange username + password for a session
// (POST /auth/login)
func (_ Unimplemented) AuthLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Invalidate the current session
// (POST /auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Identity of the authenticated user
// (GET /auth/me)
func (_ Unimplemented) GetCurrentUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Complete a pre-session MFA challenge
// (POST /auth/mfa/complete)
func (_ Unimplemented) AuthMfaComplete(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create the first admin user
// (POST /auth/setup)
func (_ Unimplemented) AuthSetup(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Report whether first-admin setup is required
// (GET /auth/setup/status)
func (_ Unimplemented) AuthSetupStatus(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Liveness probe
// (GET /healthz)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List instances visible to the user
// (GET /instances)
func (_ Unimplemented) ListInstances(w http.ResponseWriter, r *http.Request, params ListInstancesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new instance (async)
// (POST /instances)
func (_ Unimplemented) CreateInstance(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete an instance (async)
// (DELETE /instances/{name})
func (_ Unimplemented) DeleteInstance(w http.ResponseWriter, r *http.Request, name InstanceName) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Fetch a single instance
// (GET /instances/{name})
func (_ Unimplemented) GetInstance(w http.ResponseWriter, r *http.Request, name InstanceName) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Start an instance (async)
// (POST /instances/{name}/start)
func (_ Unimplemented) StartInstance(w http.ResponseWriter, r *http.Request, name InstanceName) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Stop an instance (async)
// (POST /instances/{name}/stop)
func (_ Unimplemented) StopInstance(w http.ResponseWriter, r *http.Request, name InstanceName) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List operations for the current user
// (GET /operations)
func (_ Unimplemented) ListOperations(w http.ResponseWriter, r *http.Request, params ListOperationsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Fetch a single operation by ID
// (GET /operations/{id})
func (_ Unimplemented) GetOperation(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Server version and build info
// (GET /version)
func (_ Unimplemented) GetVersion(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// AuthLogin operation middleware
func (siw *ServerInterfaceWrapper) AuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthMfaComplete operation middleware
func (siw *ServerInterfaceWrapper) AuthMfaComplete(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthMfaComplete(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthSetup operation middleware
func (siw *ServerInterfaceWrapper) AuthSetup(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthSetup(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthSetupStatus operation middleware
func (siw *ServerInterfaceWrapper) AuthSetupStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthSetupStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListInstances operation middleware
func (siw *ServerInterfaceWrapper) ListInstances(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListInstancesParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListInstances(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateInstance operation middleware
func (siw *ServerInterfaceWrapper) CreateInstance(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateInstance(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteInstance operation middleware
func (siw *ServerInterfaceWrapper) DeleteInstance(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name InstanceName

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteInstance(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetInstance operation middleware
func (siw *ServerInterfaceWrapper) GetInstance(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name InstanceName

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetInstance(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartInstance operation middleware
func (siw *ServerInterfaceWrapper) StartInstance(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name InstanceName

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartInstance(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StopInstance operation middleware
func (siw *ServerInterfaceWrapper) StopInstance(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name InstanceName

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StopInstance(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListOperations operation middleware
func (siw *ServerInterfaceWrapper) ListOperations(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListOperationsParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListOperations(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOperation operation middleware
func (siw *ServerInterfaceWrapper) GetOperation(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOperation(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVersion(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.AuthLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/me", wrapper.GetCurrentUser)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/mfa/complete", wrapper.AuthMfaComplete)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/setup", wrapper.AuthSetup)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/setup/status", wrapper.AuthSetupStatus)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/instances", wrapper.ListInstances)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/instances", wrapper.CreateInstance)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/instances/{name}", wrapper.DeleteInstance)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/instances/{name}", wrapper.GetInstance)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/instances/{name}/start", wrapper.StartInstance)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/instances/{name}/stop", wrapper.StopInstance)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/operations", wrapper.ListOperations)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/operations/{id}", wrapper.GetOperation)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/version", wrapper.GetVersion)
	})

	return r
}

type BadRequestJSONResponse Error

type ConflictJSONResponse Error

type NotFoundJSONResponse Error

type RateLimitedJSONResponse Error

type ServiceUnavailableJSONResponse Error

type UnauthorizedJSONResponse Error

type AuthLoginRequestObject struct {
	Body *AuthLoginJSONRequestBody
}

type AuthLoginResponseObject interface {
	VisitAuthLoginResponse(w http.ResponseWriter) error
}

type AuthLogin200ResponseHeaders struct {
	SetCookie string
}

type AuthLogin200JSONResponse struct {
	Body    AuthTokenEnvelope
	Headers AuthLogin200ResponseHeaders
}

func (response AuthLogin200JSONResponse) VisitAuthLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type AuthLogin202JSONResponse AuthTokenEnvelope

func (response AuthLogin202JSONResponse) VisitAuthLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type AuthLogin204ResponseHeaders struct {
	SetCookie string
}

type AuthLogin204Response struct {
	Headers AuthLogin204ResponseHeaders
}

func (response AuthLogin204Response) VisitAuthLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(204)
	return nil
}

type AuthLogin400JSONResponse struct{ BadRequestJSONResponse }

func (response AuthLogin400JSONResponse) VisitAuthLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type AuthLogin401JSONResponse struct{ UnauthorizedJSONResponse }

func (response AuthLogin401JSONResponse) VisitAuthLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type AuthLogin429JSONResponse struct{ RateLimitedJSONResponse }

func (response AuthLogin429JSONResponse) VisitAuthLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutRequestObject struct {
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204Response struct {
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type Logout401JSONResponse struct{ UnauthorizedJSONResponse }

func (response Logout401JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetCurrentUserRequestObject struct {
}

type GetCurrentUserResponseObject interface {
	VisitGetCurrentUserResponse(w http.ResponseWriter) error
}

type GetCurrentUser200JSONResponse User

func (response GetCurrentUser200JSONResponse) VisitGetCurrentUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetCurrentUser401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetCurrentUser401JSONResponse) VisitGetCurrentUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type AuthMfaCompleteRequestObject struct {
	Body *AuthMfaCompleteJSONRequestBody
}

type AuthMfaCompleteResponseObject interface {
	VisitAuthMfaCompleteResponse(w http.ResponseWriter) error
}

type AuthMfaComplete200ResponseHeaders struct {
	SetCookie string
}

type AuthMfaComplete200JSONResponse struct {
	Body    AuthTokenEnvelope
	Headers AuthMfaComplete200ResponseHeaders
}

func (response AuthMfaComplete200JSONResponse) VisitAuthMfaCompleteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type AuthMfaComplete204Response struct {
}

func (response AuthMfaComplete204Response) VisitAuthMfaCompleteResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type AuthMfaComplete400JSONResponse struct{ BadRequestJSONResponse }

func (response AuthMfaComplete400JSONResponse) VisitAuthMfaCompleteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type AuthMfaComplete401JSONResponse struct{ UnauthorizedJSONResponse }

func (response AuthMfaComplete401JSONResponse) VisitAuthMfaCompleteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type AuthMfaComplete429JSONResponse struct{ RateLimitedJSONResponse }

func (response AuthMfaComplete429JSONResponse) VisitAuthMfaCompleteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type AuthSetupRequestObject struct {
	Body *AuthSetupJSONRequestBody
}

type AuthSetupResponseObject interface {
	VisitAuthSetupResponse(w http.ResponseWriter) error
}

type AuthSetup201JSONResponse User

func (response AuthSetup201JSONResponse) VisitAuthSetupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type AuthSetup400JSONResponse struct{ BadRequestJSONResponse }

func (response AuthSetup400JSONResponse) VisitAuthSetupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type AuthSetup401JSONResponse struct{ UnauthorizedJSONResponse }

func (response AuthSetup401JSONResponse) VisitAuthSetupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type AuthSetup409JSONResponse struct{ ConflictJSONResponse }

func (response AuthSetup409JSONResponse) VisitAuthSetupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type AuthSetup503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response AuthSetup503JSONResponse) VisitAuthSetupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type AuthSetupStatusRequestObject struct {
}

type AuthSetupStatusResponseObject interface {
	VisitAuthSetupStatusResponse(w http.ResponseWriter) error
}

type AuthSetupStatus200JSONResponse SetupStatus

func (response AuthSetupStatus200JSONResponse) VisitAuthSetupStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type AuthSetupStatus503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response AuthSetupStatus503JSONResponse) VisitAuthSetupStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListInstancesRequestObject struct {
	Params ListInstancesParams
}

type ListInstancesResponseObject interface {
	VisitListInstancesResponse(w http.ResponseWriter) error
}

type ListInstances200JSONResponse []Instance

func (response ListInstances200JSONResponse) VisitListInstancesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListInstances401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListInstances401JSONResponse) VisitListInstancesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateInstanceRequestObject struct {
	Body *CreateInstanceJSONRequestBody
}

type CreateInstanceResponseObject interface {
	VisitCreateInstanceResponse(w http.ResponseWriter) error
}

type CreateInstance202JSONResponse Operation

func (response CreateInstance202JSONResponse) VisitCreateInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type CreateInstance400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateInstance400JSONResponse) VisitCreateInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateInstance401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateInstance401JSONResponse) VisitCreateInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateInstance409JSONResponse struct{ ConflictJSONResponse }

func (response CreateInstance409JSONResponse) VisitCreateInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteInstanceRequestObject struct {
	Name InstanceName `json:"name"`
}

type DeleteInstanceResponseObject interface {
	VisitDeleteInstanceResponse(w http.ResponseWriter) error
}

type DeleteInstance202JSONResponse Operation

func (response DeleteInstance202JSONResponse) VisitDeleteInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteInstance401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteInstance401JSONResponse) VisitDeleteInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteInstance404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteInstance404JSONResponse) VisitDeleteInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteInstance409JSONResponse struct{ ConflictJSONResponse }

func (response DeleteInstance409JSONResponse) VisitDeleteInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type GetInstanceRequestObject struct {
	Name InstanceName `json:"name"`
}

type GetInstanceResponseObject interface {
	VisitGetInstanceResponse(w http.ResponseWriter) error
}

type GetInstance200JSONResponse Instance

func (response GetInstance200JSONResponse) VisitGetInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetInstance401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetInstance401JSONResponse) VisitGetInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetInstance404JSONResponse struct{ NotFoundJSONResponse }

func (response GetInstance404JSONResponse) VisitGetInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type StartInstanceRequestObject struct {
	Name InstanceName `json:"name"`
}

type StartInstanceResponseObject interface {
	VisitStartInstanceResponse(w http.ResponseWriter) error
}

type StartInstance202JSONResponse Operation

func (response StartInstance202JSONResponse) VisitStartInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type StartInstance401JSONResponse struct{ UnauthorizedJSONResponse }

func (response StartInstance401JSONResponse) VisitStartInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type StartInstance404JSONResponse struct{ NotFoundJSONResponse }

func (response StartInstance404JSONResponse) VisitStartInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type StartInstance409JSONResponse struct{ ConflictJSONResponse }

func (response StartInstance409JSONResponse) VisitStartInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type StopInstanceRequestObject struct {
	Name InstanceName `json:"name"`
	Body *StopInstanceJSONRequestBody
}

type StopInstanceResponseObject interface {
	VisitStopInstanceResponse(w http.ResponseWriter) error
}

type StopInstance202JSONResponse Operation

func (response StopInstance202JSONResponse) VisitStopInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type StopInstance401JSONResponse struct{ UnauthorizedJSONResponse }

func (response StopInstance401JSONResponse) VisitStopInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type StopInstance404JSONResponse struct{ NotFoundJSONResponse }

func (response StopInstance404JSONResponse) VisitStopInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type StopInstance409JSONResponse struct{ ConflictJSONResponse }

func (response StopInstance409JSONResponse) VisitStopInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ListOperationsRequestObject struct {
	Params ListOperationsParams
}

type ListOperationsResponseObject interface {
	VisitListOperationsResponse(w http.ResponseWriter) error
}

type ListOperations200JSONResponse []Operation

func (response ListOperations200JSONResponse) VisitListOperationsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListOperations401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListOperations401JSONResponse) VisitListOperationsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetOperationRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetOperationResponseObject interface {
	VisitGetOperationResponse(w http.ResponseWriter) error
}

type GetOperation200JSONResponse Operation

func (response GetOperation200JSONResponse) VisitGetOperationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetOperation401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetOperation401JSONResponse) VisitGetOperationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetOperation404JSONResponse struct{ NotFoundJSONResponse }

func (response GetOperation404JSONResponse) VisitGetOperationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetVersionRequestObject struct {
}

type GetVersionResponseObject interface {
	VisitGetVersionResponse(w http.ResponseWriter) error
}

type GetVersion200JSONResponse Version

func (response GetVersion200JSONResponse) VisitGetVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Exchange username + password for a session
	// (POST /auth/login)
	AuthLogin(ctx context.Context, request AuthLoginRequestObject) (AuthLoginResponseObject, error)
	// Invalidate the current session
	// (POST /auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// Identity of the authenticated user
	// (GET /auth/me)
	GetCurrentUser(ctx context.Context, request GetCurrentUserRequestObject) (GetCurrentUserResponseObject, error)
	// Complete a pre-session MFA challenge
	// (POST /auth/mfa/complete)
	AuthMfaComplete(ctx context.Context, request AuthMfaCompleteRequestObject) (AuthMfaCompleteResponseObject, error)
	// Create the first admin user
	// (POST /auth/setup)
	AuthSetup(ctx context.Context, request AuthSetupRequestObject) (AuthSetupResponseObject, error)
	// Report whether first-admin setup is required
	// (GET /auth/setup/status)
	AuthSetupStatus(ctx context.Context, request AuthSetupStatusRequestObject) (AuthSetupStatusResponseObject, error)
	// Liveness probe
	// (GET /healthz)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// List instances visible to the user
	// (GET /instances)
	ListInstances(ctx context.Context, request ListInstancesRequestObject) (ListInstancesResponseObject, error)
	// Create a new instance (async)
	// (POST /instances)
	CreateInstance(ctx context.Context, request CreateInstanceRequestObject) (CreateInstanceResponseObject, error)
	// Delete an instance (async)
	// (DELETE /instances/{name})
	DeleteInstance(ctx context.Context, request DeleteInstanceRequestObject) (DeleteInstanceResponseObject, error)
	// Fetch a single instance
	// (GET /instances/{name})
	GetInstance(ctx context.Context, request GetInstanceRequestObject) (GetInstanceResponseObject, error)
	// Start an instance (async)
	// (POST /instances/{name}/start)
	StartInstance(ctx context.Context, request StartInstanceRequestObject) (StartInstanceResponseObject, error)
	// Stop an instance (async)
	// (POST /instances/{name}/stop)
	StopInstance(ctx context.Context, request StopInstanceRequestObject) (StopInstanceResponseObject, error)
	// List operations for the current user
	// (GET /operations)
	ListOperations(ctx context.Context, request ListOperationsRequestObject) (ListOperationsResponseObject, error)
	// Fetch a single operation by ID
	// (GET /operations/{id})
	GetOperation(ctx context.Context, request GetOperationRequestObject) (GetOperationResponseObject, error)
	// Server version and build info
	// (GET /version)
	GetVersion(ctx context.Context, request GetVersionRequestObject) (GetVersionResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// AuthLogin operation middleware
func (sh *strictHandler) AuthLogin(w http.ResponseWriter, r *http.Request) {
	var request AuthLoginRequestObject

	var body AuthLoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AuthLogin(ctx, request.(AuthLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AuthLogin")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AuthLoginResponseObject); ok {
		if err := validResponse.VisitAuthLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(w http.ResponseWriter, r *http.Request) {
	var request LogoutRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCurrentUser operation middleware
func (sh *strictHandler) GetCurrentUser(w http.ResponseWriter, r *http.Request) {
	var request GetCurrentUserRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCurrentUser(ctx, request.(GetCurrentUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCurrentUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCurrentUserResponseObject); ok {
		if err := validResponse.VisitGetCurrentUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AuthMfaComplete operation middleware
func (sh *strictHandler) AuthMfaComplete(w http.ResponseWriter, r *http.Request) {
	var request AuthMfaCompleteRequestObject

	var body AuthMfaCompleteJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AuthMfaComplete(ctx, request.(AuthMfaCompleteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AuthMfaComplete")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AuthMfaCompleteResponseObject); ok {
		if err := validResponse.VisitAuthMfaCompleteResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AuthSetup operation middleware
func (sh *strictHandler) AuthSetup(w http.ResponseWriter, r *http.Request) {
	var request AuthSetupRequestObject

	var body AuthSetupJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AuthSetup(ctx, request.(AuthSetupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AuthSetup")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AuthSetupResponseObject); ok {
		if err := validResponse.VisitAuthSetupResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AuthSetupStatus operation middleware
func (sh *strictHandler) AuthSetupStatus(w http.ResponseWriter, r *http.Request) {
	var request AuthSetupStatusRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AuthSetupStatus(ctx, request.(AuthSetupStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AuthSetupStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AuthSetupStatusResponseObject); ok {
		if err := validResponse.VisitAuthSetupStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListInstances operation middleware
func (sh *strictHandler) ListInstances(w http.ResponseWriter, r *http.Request, params ListInstancesParams) {
	var request ListInstancesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListInstances(ctx, request.(ListInstancesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListInstances")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListInstancesResponseObject); ok {
		if err := validResponse.VisitListInstancesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateInstance operation middleware
func (sh *strictHandler) CreateInstance(w http.ResponseWriter, r *http.Request) {
	var request CreateInstanceRequestObject

	var body CreateInstanceJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateInstance(ctx, request.(CreateInstanceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateInstance")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateInstanceResponseObject); ok {
		if err := validResponse.VisitCreateInstanceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteInstance operation middleware
func (sh *strictHandler) DeleteInstance(w http.ResponseWriter, r *http.Request, name InstanceName) {
	var request DeleteInstanceRequestObject

	request.Name = name

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteInstance(ctx, request.(DeleteInstanceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteInstance")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteInstanceResponseObject); ok {
		if err := validResponse.VisitDeleteInstanceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetInstance operation middleware
func (sh *strictHandler) GetInstance(w http.ResponseWriter, r *http.Request, name InstanceName) {
	var request GetInstanceRequestObject

	request.Name = name

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetInstance(ctx, request.(GetInstanceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetInstance")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetInstanceResponseObject); ok {
		if err := validResponse.VisitGetInstanceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StartInstance operation middleware
func (sh *strictHandler) StartInstance(w http.ResponseWriter, r *http.Request, name InstanceName) {
	var request StartInstanceRequestObject

	request.Name = name

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.StartInstance(ctx, request.(StartInstanceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StartInstance")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(StartInstanceResponseObject); ok {
		if err := validResponse.VisitStartInstanceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StopInstance operation middleware
func (sh *strictHandler) StopInstance(w http.ResponseWriter, r *http.Request, name InstanceName) {
	var request StopInstanceRequestObject

	request.Name = name

	var body StopInstanceJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.StopInstance(ctx, request.(StopInstanceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StopInstance")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(StopInstanceResponseObject); ok {
		if err := validResponse.VisitStopInstanceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListOperations operation middleware
func (sh *strictHandler) ListOperations(w http.ResponseWriter, r *http.Request, params ListOperationsParams) {
	var request ListOperationsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListOperations(ctx, request.(ListOperationsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListOperations")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListOperationsResponseObject); ok {
		if err := validResponse.VisitListOperationsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOperation operation middleware
func (sh *strictHandler) GetOperation(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetOperationRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOperation(ctx, request.(GetOperationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOperation")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOperationResponseObject); ok {
		if err := validResponse.VisitGetOperationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVersion operation middleware
func (sh *strictHandler) GetVersion(w http.ResponseWriter, r *http.Request) {
	var request GetVersionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetVersion(ctx, request.(GetVersionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVersion")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetVersionResponseObject); ok {
		if err := validResponse.VisitGetVersionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Dz7b9u2uv8KoXuA02LyM4+mKfZDmqZtumTJidPdi9PkxrT0yeYqkRpJOXGL3L/9gg89TdlOm3QbcDag",
	"rS2K/Pi9n/7qBSxJGQUqhbf/1UsxxwlI4PrTMRUS0wB+xQmozyGIgJNUEka9/eIpojgBlGI5Q8XrXc/3",
	"iFqkvvZ8j+odzF++x+GPjHAIvX3JM/A9EcwgwWtO6KITdgs8wAJQDFLB6KOQTIkUPsI0RLNFOgMqEKPx",
	"ontFT/Ed2t1CwQxz0UWnmZBISMwluiVyZndAjJstulfU8z24w0kaK0BvYdIZeL4CXwJXsPzvJ9z50u+8",
	"vLZ/d66/9v3d4f0/PN+Ti1S9JCQndOrd39+rK4qUUQEaj69xeAF/ZCCk+hQwKoHqf+I0jUmA1XV7vwt1",
	"568VZPyDQ+Tte//VK2nUM09F74hzxs1RdZyd4jhiPIEQcXvkve8dMhrFJPgBx48kloACex56Bt1pF5Gc",
	"jjjmgMMFgjsiNNnsZ55RSuj0uYL1VybfsoyGTw/rBQiWccVeTKJIn3nvexdYwglJiIQfAMIlYyjBdJET",
	"SygIRsDnJICPFM8xifEkhh+BCyOSKGYBjpEwICj5ECCzFCVYAic4RkSgrALYve99pDiTM8bJlx+BsVMi",
	"BKFTBRmhcxyTEAkQQj1Ui+37avuDTM4u2WegR3QOMUsdKuzD6OxXBPYx4iAzTiFEkwVSV0JRzG4FkjMs",
	"EREi0+hQtyM0A4Tzc5WuSzlLgUti5D3Ecu0FC+gurKbwjNrINeMns8t1oV3Y5HcItDQvv7p0MbUE5ToI",
	"qZ1QxDhKsRC3jIdaX56+PTA3XL4ADgIQ4kaqQ5Y3PwqHOzuDlx1BpgpbH/77EpkXkH6hi845CKAS3c6A",
	"6mOI0DKW307hEUdK/6qHCjkxSIvJUgfD4sNs8i4gZ+TD238fXVz+a/ThZbfbXda36qWUcBA3xAHtgQat",
	"o0FDMYlAkgQQoUhAwGgoaoe+7Pd9LyGUJFni7Q+KowiVMAWuzkoifFOSqXnaJc/A3FvOoMT3LRYaR6lU",
	"7JVJdHl2ea7RgDgEbA58gQIWgsKUkCSOC1zVwItwLKAAasJYDJjmQLVQ6yzFf2SAUg4dy7Aa6w1SKaNp",
	"4B5XLzhWACkjXSdN0N+LtvGL4d5gsrMdvsQTiHZfBMNBP9yC7Zd46KKRPvDGfN2E8TVgDtzAhNQSza0K",
	"gzXGUjBQRZhP9g0lHiVU9rtle1yXqxoBXfJldM8SkCOJaYh5iEA9d6uN7bs7LVs7d3eF+DnkS5HaecAk",
	"Bh8lOJgRCh1lG9U39kD1Up0MlMkbY7cc+A5BYhIbcQ5Dos7A8XkFDON7NZnFrENC8iyQmRJWrc/vZO3o",
	"r15EIA5zl+7egcUEhMBTxzXfZwmm5eXsuvrNCo+hNM3ryKpxWh7rIux7wLGcLUP0BkPClHKYA1XcluJF",
	"zHC4TDdCg0zccMDBLDfLq8T/WC1HggWfQVp2CCFEkumnMRYSpZxN6nc3ZFkWcSGxzIRDv02nHKbK6wrN",
	"NWb6lsrZlVAVGfbZU+Sechwaxi/RrR+tRq893oXW3E1fhu2QUYkJNY72nHCZ4bhj2bv0CgXFqZgx6bBD",
	"PJgRCZoRHbuff0TVFXUWutvbvdnddklGwAFLCG+wXBFy6EVKWSpzISROUvTs4u0h2traevm8ftKwP9zt",
	"9Hc6/a3LwXC/39/v9//t+Z5yw9URypBDR23jAoYkTiEZGc9UP0U4JlgoFEaEToGnnFDZkBe1TuyHMCGY",
	"9gZbzpPS+bbjwufzbYTDkIMQIBAW1qpbJs2JVDvukzfod9X/O4ofiIRErN5YmduQSQlh548Mh0q7J/UL",
	"FBu6LIf5AnOOF/Yiu87zdh9+kSjcHu7vr7lHsW8d5vzdDUCmG0TQz4y6ICFQSSICvMFmeUy6dFibZjjM",
	"OFe2XTk9wSKIYVkn2MDLU5uwNAWlZiPOvoAOh7Ud1PtzWVml/llTH+UuLYhovfhnQlWgmjIujQHVOKhC",
	"GOQqxPO9hgapA1FduFqV2SyEXuRvotgOtcJYvoYN6tGEhQvtsYzPz0aXqJfzmhg7TIhb3o/bBR0dmTuK",
	"fTRuyvnYv6L5l9kkozLrDbe7/e2xb5xLMcPDnd3ado1Mxyaaw829b0BoZ57UsjSPl0axjGcOjnAWy8IB",
	"buAu0i6qb/M7JEkgJFhCvLBRRq7LN/OlS5a1h9ZYaxUjS2aOgh/DwIaVVjHuSLK0knlq8fVa2bf3VZ10",
	"31NS72DliPEAHkIeoCEaHb/75fjkxFJGWUWWSc1DgEPEIrXg8ujiFE05bmjrdoqZXW5sRFcDaau/lKIy",
	"qxS1bjGR+ub6sCiLkZhlMmS3FE0gYlzHIQGh0xocassE35kYcbcWMfaXI0aXb3zCpoS2EuajAK4twk9l",
	"ABlw0HYBxwKJbJIQZUzVFcY9nMlZL1Y7OmiUb+CMi1lGZXnEsyAGzJWrj1RAii5PRjosbJihgHEOgUQz",
	"xgWgiZbshRI99bji9RQna2SdAJ0q13u4s6vRlX/ec4h9Zu/fDnO+og4ZjkkA9eN2t2unDdZJVnG0X8Lv",
	"ErDTtweHJm0BrWTMQ/w8wO/oAD/ljEWa5/BSTB7McBwDNcFQnY4PC/CLjWxIXQ1RlxjmQWH9ClIOdh20",
	"zC9/4w55z6jxjBtZEDFTIhhmaheTKgHKWRwn0HR8D14fvukcvX33vnP84ZeTzumvZ+erOWDXmZqQaQuA",
	"I3LX0RUCA4aGLuIs0T6l4pZ/Cp0rVLIZYKnImqYN13a4tb2z24CqBtRu3UIq8/h111lZWM5kGKZw8ehZ",
	"ChybayzJkVjQALF8AZIcB58VrhUZuCPwXRUyFecYxWQ4UBP1SQImcGdnajlH49MhItA4wiTOOIwd8RKK",
	"QAYzpFaAM4VCwlW3LR119Ozjx+M3aP6icc/+YC/awtv9Tr/f73deqD/21B/9yn/Ve2cZccKhnItVkKjn",
	"PtKllnER5xiSjZUGKr8MQamssTvZYl9xQZByNlUB0E0KPLDJ/QZLpSlndyTBUus4vRpNQN4CUNTXSbFB",
	"v4+eTUDIDkQR47KOre1hxaoO1lnV9VFPyd0r4p8UaGgil0oklOmcoyKM4R3P9wKFnzhu5k1WBT6YT0G6",
	"YgZbdFIKpIQRB1IgRpsFM2WLNg0DszRsldETbMqfEjrBDGvD8DAB3dlUQBsqSjO05t+CYrUETA1slxYb",
	"gczafdi3hAvZwWFCaM1FSuNMlGF/HENexyoSyZu6SceUqC2ROSNf96NdIg18qwOQG9HKFRFX7rS2VOMe",
	"yKA3gzgmdNrTa0w1pKEGfo0/RBfD0Qv87mV2OcK/xB92pqfxxR7dC7PfD474m/8R/8peZPHbo+2f199q",
	"MNyr3Wpr+CBPr472Fn9PPXt8f6+O7VaeHLXonypLGoLYaimJiVwss545bG1FicSAKNOYEKZ+rnWq9eb0",
	"JmMUYGojUM38kQLFoHCDFHMz4VuHy4UHFai4a4/WHYJQA2xNpev2qxyL3NuvpWKfKAsbtpVjqhdQtr52",
	"6KCyP6Gymm6uWCoibgyrummbl7omjEkhOU4rTL9Z/Pu9AdMGKrwiKMV1aorcxR+/ARdO/3MEXEWYk4zE",
	"IUpA4hBL7Ej/p+Rm3rbHxdHoEh2cH6ME/854x64zfUgCpsuhwtxpNTUMN5ovlsuSGj5HAQD10PHoDO3t",
	"9gePyYUBSxLiEIR3RCLzTEVGXKLR+wPDMoRivtDVZXUPqRV+HaCtPp5sR84kdStqbT1MQIKVHKMct+bV",
	"ho/bHXT7a3koP8qv0XSZZ7SpCzJO5GIUzCDJy6XsMwGlV1ysZENevcb0aZg41ySzqsEuGinHEGeSJVjp",
	"pzheqJUak5zdCuCv0OHJMRKScRCISJTREDga/1+vGzAakWnFjOpjx0Wjmzm/bHWzC2/y5pSyJpCSX2Bh",
	"WlsIjVjeMoNNe5Z9/TX5gjkHdEzDTOEUlN+U8VjtLGUq9nu9KZGzbNINWNKzqzvl6hxQb6mB5r15oIIj",
	"jATEUWfGhITQR4LQaQwdqmLcIhmprcxvpyjBFE9BSRVKYyx1BeeKXs6IDrMUCuf97kCxisYsEkq37Fdj",
	"Y8KoX3q2hxcf35i+vdIJTpkGrXtFr+hBHCOgYcoIlSKnQ28+6I0R5tqTV8r5lsgZofroLnrNAeso1ri4",
	"AokZSctXh72xSX4ryGzXjMX2wbvzk86W5uM6jm9vb7tTmnUZn/bsa6KHp2msVndnMolN/lFqWchRe3B+",
	"7FXEy8rIve+xFChOiRLLbr+7ZTLjM83jFUbVDilzubu/4ZgoDSJqzi5W0Z8Ov3Xg4hshEGWHEpoTrEh0",
	"RccNthxbuelqvlfUuIUJCmICGuvC+BG1Nql/iiva6ACqd/9YmyNMoyVQRajQpE84BEDmgPAVbc19VXPB",
	"ZY+VJlzBKceh9TN0ItV2lIKQr1m4eLQWtFqS1tGJpryfKh2WGlubbaDDfn8D4Co9FnkfWb0da0VjVLUP",
	"yrQy1ZqVcgei0omTN82UvXMbN64VbXUO3Gjc5QwZZbFSvVKgNvbTnGeSlIqdawyl/SNl5y1XqnvOAIe2",
	"R3kEsnNodO862yBAVsQkymKkxU1t2NaBXPT8lMcgczia47jZFtW43c/dbvcVOsdy9nPvFXovZXpG48Ur",
	"NFIWDl6hEU5gRCT8fILvXqFTfNc5mMLPu/3tvb7LoiosD/vDb2OhOiOYAKCSU16f+n1kBjkvOhFtV5yv",
	"2+KUJkgyIdEE8r5AZc1NLabUZ9roKEPf9TRSHH0Nr41B76hdsCTKWMQNpiwbJCPdXqWo29GNcP9hNd/b",
	"NtrKRelCq/Uqne36lcH6V2rtwuql4cv1L1WbsqtOorf/6dr3RJYkmC+8fe/ozqa3MkcNzRRdKg4Zngrl",
	"nCp4vGu1bWGEWSbbrfAFzNlnME5PzpETltGi12SlmtNVNu1cGi7rCGL6+urW7cQAsWRCttt5z/ZDq4is",
	"iw7NMa0G/xvpdV/F9nFxoL52YDOv6zFsgq2W/KixArp9lrOIxKA8gbzcUkd048Tibk1kvgNp08I6ZfFN",
	"dnkz5af3b3MW7H0eBfU2o5LjBi8lXVahP8K9XLtu4mziSvGLccTcRTs8xcp1s5QrvLsrWrp27XVIdFBX",
	"zKaxxjqy2nUVOIEGobU84Wp/d9GUi0Uh90alG/3b4kaeRjgv5z7YmawY2wcZ1FrZMS8SbmxkHQVo17BE",
	"zbE2KFI4a5ami97i/ziwFcz95d3X5emJv48f67BjdZzXHLKcDa3Z+ht6Jrm0rmr7WKGydTa+XVcXJSCd",
	"8u9MGJOm+NBFOkWTZ1J01icf3sqHPkxp4Yo2awtW7lYU0nS+8YquqDC1KFxdQXmiuL1WMXSI9tuyKtJM",
	"o7hvuYFeHDxML1arHmXKeLuWMiahri+UxQMTtJW5flv/2ljvtbkmVXxkIm+XtLHVD5O1/gayVoyx3vve",
	"Tn9r/QuOScqVMuosna3zpjSn9Mp2hJVu7e0M5AxMwcfOa1gnNl6gGRboC/C8yqfTcSSObYxc+l1GstsF",
	"a5QX2r/Pejcrk5b1HyCFFhDXnLAWL4O07lPR80I3lhc4j5Yqs0QUc3ZuAptZmi8bRSthY4pIt1toIprG",
	"fjs2pMvAKIrx1Bmn2BmlJwxR7AkOoti6DxEoS1ci9qSYlOJsUjVbCUhsUVd0EW+EvGI1mhOhszU2xFsO",
	"bHzEbOdyvEARiSVwE1Hk3LQUShMhjwto/NqPHHz62j4Bp3vIzAF5leePDPiiLPIUHS1tftdJvfVIXcps",
	"iCaLB85hbNZ4dH/9nZzTqB9zjnWMWdRtTIegxnIxMLOK24rhsKWpGEfWWHkelcPEY0TKetNW9mro9vLk",
	"63u/xdca6fZr7eiT2rQY5HFrF1VZu2iuLLjyla50oXGv+Eb0vpLwfmwTkVWPvs7KxkIVOH0aB6ox9uIg",
	"1HHj3hWJWu8rDR8N0LLD1QHjWaW3zqSYN0X7X9jvuXe4KxhRuC1Z8RkWCxo8b2Hqmma28x2GxfNk0Hpm",
	"N2ufntnf6HNqzP5nMJIGQ/ERW+Ko7yD79vqXil9C+U4+MXiskXA1k/jr7XWRebWzu0ptM1ofs1zybdpJ",
	"2X905bVSbeWz8T+IfDVqvNVN59h2WxQIazdCdW/FdWa5pFf7yab7a5e494qxuu/aeq15tON4eS43b3NT",
	"MJRDg+u0xzIfjdSuf7pS0FD8bTWCgX5zhdDCRiz9IVzE0rVMVJ9lVOTnLBZ6eg/QT/mY4bcwG0t/kLdV",
	"ndV0ujNFXMJSGwEJ9MzcUEWTfjFMaccgn3v3f550aBj/rsLB0gfKRunabBTscghqEyrVkU7bj/hIYe9Z",
	"Cdg3xb1a4Eo4u98aB1dmxMz2bYHwUw3k3PtL1QYza4RolkyAK/+Fg8hiqWEzxZy268YkIbJxWztuvNP3",
	"W84xuyPdG1crt+xUx4mH636A6qkC/FJaHxrhVzTB+hD/osn6jxbiV6QptxK5k9oI8iuHN8VXRyYbyXDh",
	"AOu8julVNB5dicnJAikb9vHj8RunP1xi7gkd4g2DZH2Pv4JDXEPf8Zs2uq1VZ21jms9bfptUjzls+suk",
	"dt7T3RH/KFOfxnevtOhvmn8WkMyVtTg4P84b9300LSYITM/1pD7Z4OTO34qe/SfjzfwIB2faR0i3yK/K",
	"RdtZknxGobydfnM5NV3fqj5c8OlaqVehd3Rx1Yn+cUxbJLRMCjP90x8zQIc4DBcIwinkv5+51E+uf11z",
	"xoTszQfesk16Q/Qcof3FMNtG8Ozw5NhHIcyf17b7KaPkbr/X6/GMFrVXnJKueltvf11cfsWIVo6zvCBd",
	"9vmXoqELIsvQHjZnBIpB24pUVVK5m06hl2/XzETLEFE+W+bbHz7zUTlsYrfRpL+/vv//AAAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
