// Code generated by tygo. DO NOT EDIT.
export type EventData = Record<string, unknown>;

//////////
// source: events.go

export const SourceHelling = 'helling';
export const SourceIncus = 'incus';
export const SourcePodman = 'podman';
export type Source = typeof SourceHelling | typeof SourceIncus | typeof SourcePodman;
export interface Event {
  id: string;
  type: string;
  time: string;
  source: Source;
  subject: string;
  data: EventData;
}
export interface IncusLifecycleEvent {
  action: string;
  source: string;
  type: string;
  metadata: EventData;
}
