// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package sqlc

import (
	"database/sql"
)

type ApiToken struct {
	ID         string        `json:"id"`
	UserID     int64         `json:"user_id"`
	Name       string        `json:"name"`
	TokenHash  string        `json:"token_hash"`
	Scopes     string        `json:"scopes"`
	CreatedAt  int64         `json:"created_at"`
	ExpiresAt  sql.NullInt64 `json:"expires_at"`
	LastUsedAt sql.NullInt64 `json:"last_used_at"`
}

type BmcEndpoint struct {
	ID        string `json:"id"`
	UserID    int64  `json:"user_id"`
	Name      string `json:"name"`
	Address   string `json:"address"`
	Port      int64  `json:"port"`
	Username  string `json:"username"`
	Password  string `json:"password"`
	Protocol  string `json:"protocol"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type Event struct {
	ID        string `json:"id"`
	Type      string `json:"type"`
	Source    string `json:"source"`
	Subject   string `json:"subject"`
	DataJson  string `json:"data_json"`
	CreatedAt int64  `json:"created_at"`
}

type EventOutbox struct {
	ID        string         `json:"id"`
	EventID   string         `json:"event_id"`
	WebhookID sql.NullString `json:"webhook_id"`
	Status    string         `json:"status"`
	Attempts  int64          `json:"attempts"`
	NextRunAt sql.NullInt64  `json:"next_run_at"`
	CreatedAt int64          `json:"created_at"`
	UpdatedAt int64          `json:"updated_at"`
}

type FirewallHostRule struct {
	ID              string         `json:"id"`
	UserID          int64          `json:"user_id"`
	Direction       string         `json:"direction"`
	Action          string         `json:"action"`
	Protocol        string         `json:"protocol"`
	SourceCidr      sql.NullString `json:"source_cidr"`
	DestinationCidr sql.NullString `json:"destination_cidr"`
	DestinationPort sql.NullInt64  `json:"destination_port"`
	Enabled         int64          `json:"enabled"`
	Comment         sql.NullString `json:"comment"`
	NftComment      string         `json:"nft_comment"`
	NftHandle       sql.NullInt64  `json:"nft_handle"`
	CreatedAt       int64          `json:"created_at"`
	UpdatedAt       int64          `json:"updated_at"`
}

type IncusUserCert struct {
	UserID           int64          `json:"user_id"`
	EncryptedCertPem sql.NullString `json:"encrypted_cert_pem"`
	EncryptedKeyPem  sql.NullString `json:"encrypted_key_pem"`
	Fingerprint      sql.NullString `json:"fingerprint"`
	Restricted       int64          `json:"restricted"`
	ProjectScope     string         `json:"project_scope"`
	ExpiresAt        sql.NullInt64  `json:"expires_at"`
	RevokedAt        sql.NullInt64  `json:"revoked_at"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
}

type K8sCluster struct {
	ID            string         `json:"id"`
	UserID        int64          `json:"user_id"`
	Name          string         `json:"name"`
	Version       string         `json:"version"`
	ControlPlanes int64          `json:"control_planes"`
	Workers       int64          `json:"workers"`
	Status        string         `json:"status"`
	Kubeconfig    sql.NullString `json:"kubeconfig"`
	CreatedAt     int64          `json:"created_at"`
	UpdatedAt     int64          `json:"updated_at"`
}

type Operation struct {
	ID        string         `json:"id"`
	UserID    int64          `json:"user_id"`
	Kind      string         `json:"kind"`
	Target    string         `json:"target"`
	IncusOpID sql.NullString `json:"incus_op_id"`
	Status    string         `json:"status"`
	Error     sql.NullString `json:"error"`
	CreatedAt int64          `json:"created_at"`
	UpdatedAt int64          `json:"updated_at"`
	Metadata  []byte         `json:"metadata"`
}

type Schedule struct {
	ID         string         `json:"id"`
	UserID     int64          `json:"user_id"`
	Name       string         `json:"name"`
	Kind       string         `json:"kind"`
	Target     string         `json:"target"`
	OnCalendar string         `json:"on_calendar"`
	Enabled    int64          `json:"enabled"`
	LastRunAt  sql.NullInt64  `json:"last_run_at"`
	NextRunAt  sql.NullInt64  `json:"next_run_at"`
	CreatedAt  int64          `json:"created_at"`
	UpdatedAt  int64          `json:"updated_at"`
	UnitName   sql.NullString `json:"unit_name"`
	LastStatus sql.NullString `json:"last_status"`
	LastError  sql.NullString `json:"last_error"`
}

type Session struct {
	ID         string `json:"id"`
	UserID     int64  `json:"user_id"`
	CreatedAt  int64  `json:"created_at"`
	ExpiresAt  int64  `json:"expires_at"`
	LastSeenAt int64  `json:"last_seen_at"`
}

type TotpRecoveryCode struct {
	ID       int64  `json:"id"`
	UserID   int64  `json:"user_id"`
	CodeHash string `json:"code_hash"`
	Used     int64  `json:"used"`
}

type TotpSecret struct {
	UserID    int64  `json:"user_id"`
	Secret    string `json:"secret"`
	Enabled   int64  `json:"enabled"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type User struct {
	ID           int64  `json:"id"`
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	CreatedAt    int64  `json:"created_at"`
	IsAdmin      int64  `json:"is_admin"`
	IncusProject string `json:"incus_project"`
}

type Webhook struct {
	ID              string `json:"id"`
	UserID          int64  `json:"user_id"`
	Name            string `json:"name"`
	Url             string `json:"url"`
	SecretEncrypted string `json:"secret_encrypted"`
	Events          string `json:"events"`
	Enabled         int64  `json:"enabled"`
	CreatedAt       int64  `json:"created_at"`
	UpdatedAt       int64  `json:"updated_at"`
}

type WebhookDelivery struct {
	ID           string         `json:"id"`
	WebhookID    string         `json:"webhook_id"`
	Event        string         `json:"event"`
	Status       string         `json:"status"`
	StatusCode   sql.NullInt64  `json:"status_code"`
	ResponseBody sql.NullString `json:"response_body"`
	Error        sql.NullString `json:"error"`
	Attempt      int64          `json:"attempt"`
	CreatedAt    int64          `json:"created_at"`
	EventID      sql.NullString `json:"event_id"`
	EventType    sql.NullString `json:"event_type"`
	LatencyMs    sql.NullInt64  `json:"latency_ms"`
	NextRetryAt  sql.NullInt64  `json:"next_retry_at"`
	DeliveredAt  sql.NullInt64  `json:"delivered_at"`
}

type WebhookEvent struct {
	WebhookID string `json:"webhook_id"`
	EventType string `json:"event_type"`
}
