// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: platform.sql

package sqlc

import (
	"context"
	"database/sql"
)

const listFirewallHostRules = `-- name: ListFirewallHostRules :many
SELECT id, user_id, direction, action, protocol, source_cidr, destination_cidr,
       destination_port, enabled, comment, nft_comment, nft_handle, created_at,
       updated_at
FROM firewall_host_rules
ORDER BY created_at DESC
`

func (q *Queries) ListFirewallHostRules(ctx context.Context) ([]FirewallHostRule, error) {
	rows, err := q.db.QueryContext(ctx, listFirewallHostRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FirewallHostRule{}
	for rows.Next() {
		var i FirewallHostRule
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Direction,
			&i.Action,
			&i.Protocol,
			&i.SourceCidr,
			&i.DestinationCidr,
			&i.DestinationPort,
			&i.Enabled,
			&i.Comment,
			&i.NftComment,
			&i.NftHandle,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentEvents = `-- name: ListRecentEvents :many
SELECT id, type, source, subject, data_json, created_at
FROM events
ORDER BY created_at DESC
LIMIT ?
`

func (q *Queries) ListRecentEvents(ctx context.Context, limit int64) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listRecentEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Source,
			&i.Subject,
			&i.DataJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedules = `-- name: ListSchedules :many
SELECT id, user_id, name, kind, target, on_calendar, enabled, last_run_at,
       next_run_at, unit_name, last_status, last_error, created_at, updated_at
FROM schedules
ORDER BY created_at DESC
`

type ListSchedulesRow struct {
	ID         string         `json:"id"`
	UserID     int64          `json:"user_id"`
	Name       string         `json:"name"`
	Kind       string         `json:"kind"`
	Target     string         `json:"target"`
	OnCalendar string         `json:"on_calendar"`
	Enabled    int64          `json:"enabled"`
	LastRunAt  sql.NullInt64  `json:"last_run_at"`
	NextRunAt  sql.NullInt64  `json:"next_run_at"`
	UnitName   sql.NullString `json:"unit_name"`
	LastStatus sql.NullString `json:"last_status"`
	LastError  sql.NullString `json:"last_error"`
	CreatedAt  int64          `json:"created_at"`
	UpdatedAt  int64          `json:"updated_at"`
}

func (q *Queries) ListSchedules(ctx context.Context) ([]ListSchedulesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSchedulesRow{}
	for rows.Next() {
		var i ListSchedulesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Kind,
			&i.Target,
			&i.OnCalendar,
			&i.Enabled,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.UnitName,
			&i.LastStatus,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooks = `-- name: ListWebhooks :many
SELECT id, user_id, name, url, secret_encrypted, events, enabled, created_at,
       updated_at
FROM webhooks
ORDER BY created_at DESC
`

func (q *Queries) ListWebhooks(ctx context.Context) ([]Webhook, error) {
	rows, err := q.db.QueryContext(ctx, listWebhooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Url,
			&i.SecretEncrypted,
			&i.Events,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
