#!/usr/bin/env bash
# scripts/plan-next-version.sh
#
# Deterministic next-version plan generator (ADR-053).
#
# After a release tag is pushed, this script reads docs/roadmap/checklist.md,
# finds the lowest version gate with open items, and writes a tracking plan
# skeleton at docs/plans/v<next-version>-plan.md.
#
# Local usage:
#   bash scripts/plan-next-version.sh
#   task plan:next-version
#
# CI usage:
#   .github/workflows/plan-next-version.yml on push tags 'v*'.
#
# Inputs:
#   docs/roadmap/checklist.md       gate headings + open items
#   git tag --list 'v*'             most-recent tag (for "since" reporting)
#   docs/decisions/*.md             ADR backlog
#   docs/audits/*.md                open audits
#   docs/plans/*.md                 prior plan files
#
# Outputs:
#   docs/plans/v<next-version>-plan.md (markdown)
#   stdout: path of the generated file + open-item count

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

CHECKLIST="docs/roadmap/checklist.md"
PLANS_DIR="docs/plans"

log() { printf '▶ %s\n' "$*"; }
done_() { printf '✓ %s\n' "$*"; }
fail() {
  printf '✗ %s\n' "$*" >&2
  exit 1
}

[ -f "$CHECKLIST" ] || fail "$CHECKLIST not found. Schema drift?"

# ---- discover the just-shipped tag (most recent annotated tag matching v*) ----

PREV_TAG="$(git tag --list 'v*' --sort=-v:refname | head -n1 || true)"
if [ -z "$PREV_TAG" ]; then
  log "No prior v* tag found; treating as initial release"
  PREV_TAG="v0.0.0"
fi

# ---- find the lowest gate with open items ----
# Each gate is "## v<version> Gate" or "## v<version>.0 Gate". Open items are
# lines starting with "- [ ]" between that heading and the next "## " heading.

NEXT_VERSION=""
OPEN_COUNT=0

awk_find_next() {
  awk '
    /^## (v[0-9]+\.[0-9]+\.[0-9]+(-[a-z]+)?) Gate$/ {
      ver = $2
      open[ver] = 0
      order[++n] = ver
      cur = ver
      next
    }
    /^## / { cur = "" }
    cur != "" && /^- \[ \]/ { open[cur]++ }
    END {
      for (i = 1; i <= n; i++) {
        v = order[i]
        if (open[v] > 0) { print v "\t" open[v]; exit }
      }
    }
  ' "$CHECKLIST"
}

read -r NEXT_VERSION OPEN_COUNT <<<"$(awk_find_next || true)"

if [ -z "${NEXT_VERSION:-}" ]; then
  done_ "All version gates closed. No next-version plan needed."
  exit 0
fi

log "Previous tag: $PREV_TAG"
log "Next version: $NEXT_VERSION ($OPEN_COUNT open items)"

# ---- assemble inputs ----

OPEN_ITEMS_BLOCK="$(awk -v target="$NEXT_VERSION" '
  $0 ~ "^## " target " Gate$" { capture = 1; next }
  capture && /^## / { exit }
  capture && /^- \[ \]/
' "$CHECKLIST")"

RECENT_ADRS="$(find docs/decisions -maxdepth 1 -name '[0-9][0-9][0-9]-*.md' 2>/dev/null | sort -r | head -10)"

OPEN_AUDITS="$(find docs/audits -maxdepth 1 -name '*.md' 2>/dev/null | sort -r | head -5)"

PRIOR_PLANS="$(find docs/plans -maxdepth 1 -name '*.md' 2>/dev/null | sort -r | head -10)"

TODAY="$(date -u +%Y-%m-%d)"
PLAN_FILE="$PLANS_DIR/${NEXT_VERSION}-plan.md"

# ---- emit plan skeleton ----

mkdir -p "$PLANS_DIR"
{
  printf '# %s Tracking Plan\n\n' "$NEXT_VERSION"
  printf '> Captured: %s\n' "$TODAY"
  printf '> Previous-tag: %s\n' "$PREV_TAG"
  printf '> Source: docs/roadmap/checklist.md (%s Gate)\n' "$NEXT_VERSION"
  printf '> Generated by: scripts/plan-next-version.sh (ADR-053)\n\n'

  printf '## Context\n\n'
  printf 'After %s shipped, %d items remain open in the %s gate per the release checklist.\n' \
    "$PREV_TAG" "$OPEN_COUNT" "$NEXT_VERSION"
  printf 'This document is a deterministic snapshot. Sequence + scope decisions are human work; edit before merging.\n\n'

  printf '## Open items in %s gate\n\n' "$NEXT_VERSION"
  if [ -n "$OPEN_ITEMS_BLOCK" ]; then
    printf '%s\n\n' "$OPEN_ITEMS_BLOCK"
  else
    printf '_(none — gate already closed; verify manually)_\n\n'
  fi

  printf '## Recent ADRs (most-recent 10)\n\n'
  if [ -n "$RECENT_ADRS" ]; then
    while IFS= read -r adr; do
      title="$(head -n1 "$adr" | sed -E 's/^# *//')"
      # shellcheck disable=SC2016 # markdown template; backticks are literal
      printf -- '- [`%s`](../../%s) — %s\n' "$(basename "$adr")" "$adr" "$title"
    done <<<"$RECENT_ADRS"
    printf '\n'
  fi

  printf '## Open audits\n\n'
  if [ -n "$OPEN_AUDITS" ]; then
    while IFS= read -r aud; do
      title="$(head -n1 "$aud" | sed -E 's/^# *//' | head -c 120)"
      # shellcheck disable=SC2016 # markdown template; backticks are literal
      printf -- '- [`%s`](../../%s) — %s\n' "$(basename "$aud")" "$aud" "$title"
    done <<<"$OPEN_AUDITS"
    printf '\n'
  fi

  printf '## Prior plans (most-recent 10)\n\n'
  if [ -n "$PRIOR_PLANS" ]; then
    while IFS= read -r p; do
      # shellcheck disable=SC2016 # markdown template; backticks are literal
      printf -- '- [`%s`](../../%s)\n' "$(basename "$p")" "$p"
    done <<<"$PRIOR_PLANS"
    printf '\n'
  fi

  cat <<'GATES'
## Verification gates

Per-PR before any phase merges:

- `task check` green
- `bash scripts/check-docs-sync.sh --strict --range "@{u}..HEAD"` green
- `task vm:parallels:dev && task vm:parallels:smoke` green (ADR-052)
- `task check:parity` green
- `vacuum lint --ruleset api/.vacuum.yaml api/openapi.yaml` zero errors

GATES
  printf 'Gate close (before tagging %s):\n\n' "$NEXT_VERSION"
  # shellcheck disable=SC2016 # markdown template; backticks are literal
  printf -- '- 0 open items in `%s` Gate section of `docs/roadmap/checklist.md`\n' "$NEXT_VERSION"
  cat <<'TAIL'
- `task changelog` regenerates `CHANGELOG.md` clean
TAIL
  # shellcheck disable=SC2016 # markdown template; backticks are literal
  printf -- '- `git tag -s %s -m "Helling %s"` then `git push --tags`\n' "$NEXT_VERSION" "$NEXT_VERSION"

} >"$PLAN_FILE"

done_ "Wrote $PLAN_FILE"
echo "$PLAN_FILE"
