// Helling WebUI — Lucide icon barrel (audit F-30 + F-51).
//
// `import * as LucideIcons` defeats tree-shake (every icon ends in the
// bundle). This barrel exports only the icons the app uses and is the
// single lookup table consumed by the `I` component in shell.jsx.
//
// To add an icon: import its PascalCase name from 'lucide-react' and add
// the kebab-case key below. Names match what callers pass via `<I n="..."/>`.

import {
  Activity,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Bell,
  BellOff,
  Box,
  Boxes,
  Calendar,
  CalendarClock,
  Camera,
  ChartLine,
  Check,
  ChevronDown,
  ChevronRight,
  Circle,
  CircleDot,
  CircleHelp,
  Clipboard,
  Container,
  Copy,
  Cpu,
  Database,
  Disc,
  Download,
  Edit,
  ExternalLink,
  Eye,
  File,
  FileText,
  Filter,
  Folder,
  FolderPlus,
  GitBranch,
  Globe,
  GripVertical,
  Hexagon,
  Info,
  Key,
  KeyRound,
  Keyboard,
  LayoutDashboard,
  LayoutGrid,
  List,
  LogOut,
  Maximize2,
  Monitor,
  MoreHorizontal,
  Network,
  OctagonX,
  Package2,
  Pause,
  Pencil,
  Play,
  Plus,
  Power,
  PowerOff,
  RefreshCw,
  RotateCw,
  Rows2,
  Rows3,
  ScrollText,
  Search,
  SearchX,
  Server,
  Settings,
  Shield,
  ShieldCheck,
  ShieldOff,
  ShoppingBag,
  Sliders,
  Square,
  Stethoscope,
  Sun,
  Terminal,
  Trash2,
  TriangleAlert,
  Upload,
  Usb,
  User,
  UserPlus,
  UserX,
  Users,
  X,
} from 'lucide-react';

export const ICONS = {
  activity: Activity,
  archive: Archive,
  'arrow-down': ArrowDown,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  bell: Bell,
  'bell-off': BellOff,
  box: Box,
  boxes: Boxes,
  calendar: Calendar,
  'calendar-clock': CalendarClock,
  camera: Camera,
  'chart-line': ChartLine,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  circle: Circle,
  'circle-dot': CircleDot,
  'circle-help': CircleHelp,
  clipboard: Clipboard,
  container: Container,
  copy: Copy,
  cpu: Cpu,
  database: Database,
  disc: Disc,
  download: Download,
  edit: Edit,
  'external-link': ExternalLink,
  eye: Eye,
  file: File,
  'file-text': FileText,
  filter: Filter,
  folder: Folder,
  'folder-plus': FolderPlus,
  'git-branch': GitBranch,
  globe: Globe,
  'grip-vertical': GripVertical,
  hexagon: Hexagon,
  info: Info,
  key: Key,
  'key-round': KeyRound,
  keyboard: Keyboard,
  'layout-dashboard': LayoutDashboard,
  'layout-grid': LayoutGrid,
  list: List,
  'log-out': LogOut,
  'maximize-2': Maximize2,
  monitor: Monitor,
  'more-horizontal': MoreHorizontal,
  network: Network,
  'octagon-x': OctagonX,
  'package-2': Package2,
  pause: Pause,
  pencil: Pencil,
  play: Play,
  plus: Plus,
  power: Power,
  'power-off': PowerOff,
  'refresh-cw': RefreshCw,
  'rotate-cw': RotateCw,
  'rows-2': Rows2,
  'rows-3': Rows3,
  'scroll-text': ScrollText,
  search: Search,
  'search-x': SearchX,
  server: Server,
  settings: Settings,
  shield: Shield,
  'shield-check': ShieldCheck,
  'shield-off': ShieldOff,
  'shopping-bag': ShoppingBag,
  sliders: Sliders,
  square: Square,
  stethoscope: Stethoscope,
  sun: Sun,
  terminal: Terminal,
  'trash-2': Trash2,
  'triangle-alert': TriangleAlert,
  upload: Upload,
  usb: Usb,
  user: User,
  'user-plus': UserPlus,
  'user-x': UserX,
  users: Users,
  x: X,
} as const;

export type IconName = keyof typeof ICONS;
