# SPDX-License-Identifier: AGPL-3.0-or-later
name: Dependabot Auto-Merge

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
        with:
          egress-policy: audit

      - uses: dependabot/fetch-metadata@08eff52bf64351f401fb50a04faf3b19cd46e9cc # v2.4.0
        id: metadata

      - name: Auto-merge patch updates (exclude GitHub Actions)
        if: >-
          steps.metadata.outputs.update-type == 'version-update:semver-patch' &&
          steps.metadata.outputs.package-ecosystem != 'github_actions'
        env:
          PR_URL: "${{ github.event.pull_request.html_url }}"
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          gh pr review "$PR_URL" --approve
          gh pr merge "$PR_URL" --auto --squash
